# Generated by Django 2.2.2 on 2019-06-11 05:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='create',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 11, 5, 15, 31, 282890, tzinfo=utc)),
        ),
    ]
