# Generated by Django 2.2.2 on 2019-06-11 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20190611_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 11, 6, 10, 3, 691487, tzinfo=utc)),
        ),
    ]
